### ISSUE TITLE
Player does not display images

### ISSUE THREAD

**Issue by foguetes** [Rainbox-dev/Dufrap#33]
Is this project active?

I tried opening a exr frame sequence but didn't get it to play anything:
![image](https://user-images.githubusercontent.com/25814516/62193710-9f34dd00-b378-11e9-9460-2cdbd291c088.png)

Here's one of the files from that sequence:
[https://github.com/foguetes/files/raw/master/Scene_04_Pierrot_Beauty.0000.exr](url)

**Comment by Nico-Duduf** [comment]
I've not been working on this project for some time, but it's in my plans to update it soon; it does not support EXR yet, but that's one of the things I'm wanting to add ASAP.

In the meantime, I'm using http://djv.sourceforge.net/
which only issue is that it does not play the sound of videos. They're releasing a v2 soon, I'll see if it's worth the effort to keep this dufrap alive, or use this djv (which is free too)
